feat(live): Automatically generate the root password

diff --git a/live/root/usr/bin/agama-password b/live/root/usr/bin/agama-password
--- a/live/root/usr/bin/agama-password
+++ b/live/root/usr/bin/agama-password
@@ -4,6 +4,8 @@
 # - Kernel boot command line (use --kernel option)
 # - Systemd ask password tool (use --systemd option)
 # - Interactively using a dialog (use --dialog option)
+# - ISO file metadata (use --iso option)
+# - Generates a random password unless already set (use --random option)
 
 MYDIR=$(realpath "$(dirname "$0")")
 export DIALOGRC="$MYDIR/../share/agama/misc/dialog.conf"
@@ -108,6 +110,34 @@ password_from_iso() {
   fi
 }
 
+# generate a random password unless a password is already set
+random_password() {
+  if grep -q '^root:!\*:' /etc/shadow; then
+    echo "Root password not set, generating a random password..."
+    # generate a random password, omit symbols and confusing characters to avoid
+    # mistakes, the password will be very likely re-typed in a different device
+    # so make the password easy to type (it cannot be copy pasted)
+    #
+    # TODO: check this with the security team
+    PASSWD=$(base64 -w 0 < /dev/random | tr -d "+/0OolI1" | head -c 8)
+
+    if [ -n "$PASSWD" ]; then
+      echo "$PASSWD" | passwd --stdin
+    else
+      # uh, the user cannot login now... =:-o
+      echo "Failed to generate a password"
+      exit 1
+    fi
+
+    # display the generated password in the console
+    mkdir -p /run/issue.d
+    echo "Password for Agama and root user: \e{lightcyan}$PASSWD\e{reset}" > /run/issue.d/99-agama-password.issue
+    # the /etc/issue or /run/issue file must exist to show the issues in console
+    # hint: run "agetty --show-issue" to see what will be displayed
+    touch /run/issue
+  fi
+}
+
 if [ "$1" = "--kernel" ]; then
   # get the password from the kernel command line
   PWD=$(awk -F 'agama.password=' '{sub(/ .*$/, "", $2); print $2}' < /proc/cmdline)
@@ -125,4 +155,6 @@ elif [ "$1" = "--systemd" ]; then
   ask_password_systemd
 elif [ "$1" = "--iso" ]; then
   password_from_iso
+elif [ "$1" = "--random" ]; then
+  random_password
 fi
